### ISSUE TITLE
Bug beim Kanal (Tunnel) zum Boss Gluth in Naxxramas 10+25ger

### ISSUE THREAD

**Issue by Runenkrieger** [AvariusProject/AvariusCore#30]
Auf der Röhren zum Boss kommt ein grüner Nebel der nicht weggeht. Sogar wenn der Boss gelegt wurde.
Egal ob im 10er oder 25ger, beides getestet. Man bleibt in fight und stirbt am Nebel.

**Comment by Exitare** [comment]
Soweit ich das in Errinnerung habe ist das auch korrekt so. Der Nebel macht immer Schaden und bleibt immer bestehen.
